import type { NextPage, GetServerSideProps } from 'next';

import supabase from '@/utils/supabase';
import signInUser from '@/client/utils/auth/signInUser';
import signOutUser from '@/client/utils/auth/signOutUser';
import { useCurrentUserQuery } from '@/client/queries/currentUser';
import PageHead from '@/client/components/PageHead';
import PageLayout from '@/client/components/layouts/PageLayout';

const Home: NextPage = () => {
  const queryData = useCurrentUserQuery();

  return (
    <PageLayout>
      <PageHead
        title="Hello world"
        description="Generated by Create Next App"
      />

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          <button
            onClick={async () => {
              await signInUser({
                email: 'jalebi.labs+a@gmail.com',
                password: 'password',
              });
            }}
          >
            Sign in
          </button>

          <button
            onClick={async () => {
              await signOutUser();
            }}
          >
            Sign out
          </button>
        </div>

        <div style={{ width: '400px' }}>
          <pre>
            {JSON.stringify(
              {
                queryData,
                session: supabase.auth.session(),
                user: supabase.auth.user(),
              },
              null,
              2
            )}
          </pre>
        </div>
      </main>
    </PageLayout>
  );
};

export default Home;
