import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import supabase from '../utils/supabase';
import useExampleQuery from '../components/useExampleQuery';
import useSignInUserMutation from '../components/useSignInUserMutation';
import signInUser from '../client-functions/signInUser';

const Home: NextPage = () => {
  const exampleQuery = useExampleQuery();
  const signInUserMutation = useSignInUserMutation();

  const x = supabase;
  const y = x.auth.session();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ width: '400px' }}>
          <pre>
            {JSON.stringify(
              { session: x.auth.session(), user: x.auth.user() },
              null,
              2
            )}
          </pre>
        </div>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          <button
            onClick={async () => {
              await signInUser({
                email: 'jalebi.labs+a@gmail.com',
                password: 'password',
              });
              // signInUserMutation.mutate({
              //   input: {
              //     email: 'jalebi.labs+a@gmail.com',
              //     password: 'password',
              //   },
              // });
            }}
          >
            Sign in
          </button>

          <button
            onClick={async () => {
              const data = await supabase.auth.signOut();
              console.log(data);
            }}
          >
            Sign out
          </button>
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const x = await supabase.auth.api.getUserByCookie(context.req);
  const y = supabase;
  return {
    props: {
      // x,
    },
  };
};

export default Home;
