import type { NextPage, GetServerSideProps } from 'next';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';

import supabase from '@/utils/supabase';
import signInUser from '@/client-functions/signInUser';
import useExampleQuery from '@/components/useExampleQuery';

const Home: NextPage = () => {
  useExampleQuery();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ width: '400px' }}>
          <pre>
            {JSON.stringify(
              { session: supabase.auth.session(), user: supabase.auth.user() },
              null,
              2
            )}
          </pre>
        </div>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          <button
            onClick={async () => {
              await signInUser({
                email: 'jalebi.labs+a@gmail.com',
                password: 'password',
              });
            }}
          >
            Sign in
          </button>

          <button
            onClick={async () => {
              const data = await supabase.auth.signOut();
              console.log(data);
            }}
          >
            Sign out
          </button>
        </div>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const x = await supabase.auth.api.getUserByCookie(context.req);
  const y = supabase;
  return {
    props: {
      // x,
    },
  };
};

export default Home;
