import type { NextPage } from 'next';

import withEnforcedLogin from '@/client/utils/auth/withEnforcedLogin';
import useExampleQuery from '@/client/components/useExampleQuery';
import PageHead from '@/client/components/PageHead';
import PageLayout from '@/client/components/layouts/PageLayout';
import PlaceholderPage from '@/client/components/ui/PlaceholderPage';

const SettingsPage: NextPage = () => {
  useExampleQuery();

  return (
    <PageLayout>
      <PageHead title="Settings" description="Generated by Create Next App" />
      <PlaceholderPage title="Settings" />
    </PageLayout>
  );
};

export const getServerSideProps = withEnforcedLogin();

export default SettingsPage;
