import type { NextPage } from 'next';
import styles from '@/styles/Home.module.css';

import withEnforcedLogin from '@/client/utils/auth/withEnforcedLogin';
import useExampleQuery from '@/client/components/useExampleQuery';
import PageHead from '@/client/components/PageHead';

const Home: NextPage = () => {
  useExampleQuery();

  return (
    <div className={styles.container}>
      <PageHead title="Settings" description="Generated by Create Next App" />

      <main className={styles.main}>Settings page</main>
    </div>
  );
};

export const getServerSideProps = withEnforcedLogin();

export default Home;
